version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
formats:
  - html
  - pdf  # Optional
python:
  install:
    - requirements: docs/requirements.txt  # If you have dependencies
mkdocs:
  configuration: mkdocs.yml    # If using MkDocs (instead of Sphinx)
